import { businessInfo } from "@/constants/business";
import { privacyLinks } from "@/features/legal/constants/privacy-links";
import type { EyeconsPrivacyPolicy } from "@/features/legal/types/privacy-policy";

export const eyeconsPrivacyEn = {
  appName: "EYECONS Stan",
  businessName: businessInfo.name,
  contactEmail: businessInfo.contactEmail,
  effectiveDate: "August 1, 2026",
  navigation: [
    { id: "overview", label: "Key information" },
    { id: "purpose", label: "Purposes" },
    { id: "data", label: "Data and retention" },
    { id: "collection", label: "Collection methods" },
    { id: "third-parties", label: "Third-party disclosure" },
    { id: "external-services", label: "Processors and overseas processing" },
    { id: "deletion", label: "Deletion" },
    { id: "rights", label: "Your rights" },
    { id: "automatic", label: "Automatic collection and choices" },
    { id: "security", label: "Security measures" },
    { id: "contact", label: "Contact and remedies" },
    { id: "changes", label: "Policy changes" },
  ],
  serverData: [
    {
      category: "Anonymous community profile",
      data: "Random identifier generated by the app, app identifier, nickname, gem balance, and creation and modification timestamps",
      purpose:
        "To provide a community profile without registration, distinguish users, manage rewards, and prevent misuse",
      retention:
        "Until a deletion request is processed or the service ends. Information required to prevent misuse or respond to disputes may be retained until that purpose is fulfilled.",
    },
    {
      category: "Community activity",
      data: "Language, posts and comments, votes, reports, and creation and modification timestamps",
      purpose:
        "To provide community features, display content, process reports, maintain service order, and respond to disputes",
      retention:
        "Until a deletion request is processed or the service ends. Posts and comments deleted by a user are hidden from view and may remain to the limited extent necessary for operations, misuse prevention, and dispute response.",
    },
    {
      category: "Advertising rewards",
      data: "App-generated identifier, app identifier, ad reward transaction identifier, reward amount, and processing time",
      purpose: "To issue rewards and prevent duplicate rewards and misuse",
      retention:
        "Until the service ends or until no longer needed to prevent duplicate rewards and misuse",
    },
    {
      category: "App usage and diagnostic information",
      data: "App instance, device, operating system, language, network and IP information; screen and feature usage; content identifiers and titles; advertising and notification events; and error information",
      purpose:
        "To deliver content, analyze usage, improve features, address errors and security issues, and prevent misuse",
      retention:
        "For the period determined by the settings and privacy policies of Google and other service providers",
    },
    {
      category: "Push notifications",
      data: "Firebase Cloud Messaging registration token, subscribed topic, notification permission status, and device and app information",
      purpose: "To send app-related notifications and manage delivery status",
      retention:
        "Until notification subscription is canceled, the app is removed, or as otherwise provided by the service provider's policy",
    },
    {
      category: "Email inquiries",
      data: "Sender email address, inquiry details, and information voluntarily provided by the user",
      purpose: "To review and answer inquiries and maintain response records",
      retention:
        "One year after the inquiry is resolved. It may be retained longer where required by law or necessary to respond to a dispute.",
    },
  ],
  localData: [
    {
      category: "Favorites",
      data: "Favorited photo and video information and save timestamps",
      purpose: "To provide the favorites list",
      retention:
        "Until the favorite is removed, app data is cleared, or the app is uninstalled",
    },
    {
      category: "Settings and identifiers",
      data: "Language and notification settings, advertising consent status, a random identifier generated by the app, and cached community profile data",
      purpose:
        "To retain settings and provide community and ad reward features",
      retention:
        "Until settings are reset, app data is cleared, or the app is uninstalled",
    },
    {
      category: "Content and cache",
      data: "Photo, video, playlist, gallery, and community lists and image cache",
      purpose:
        "To display screens, improve loading speed, and reduce data usage",
      retention:
        "Until refreshed or cleared by the app, app data is cleared, or the app is uninstalled. Images saved to the device gallery remain until the user deletes them.",
    },
  ],
  externalServices: [
    {
      provider: "Supabase, Inc.",
      service: "Supabase Database and Edge Functions",
      relationship: "Data processing service provider",
      transferBasis:
        "Overseas processing and storage necessary to provide the service (Article 28-8(1)(3) of the Korean Personal Information Protection Act)",
      data: "App-generated identifier, app identifier, nickname, gem balance, community activity, reports, reward transaction information, IP address, and other network information",
      purpose:
        "To store and process anonymous community data, issue ad rewards, and prevent duplicate rewards and misuse",
      location: "Eastern United States (Northern Virginia)",
      timingAndMethod:
        "Transferred over an encrypted network when community or ad reward features are used",
      retention:
        "According to the retention periods in this policy and Supabase backup and service policies",
      refusalAndEffect:
        "No transfer occurs if these features are not used. If the transfer is refused, community and ad reward features cannot be used.",
      policyUrl: privacyLinks.supabasePrivacy,
    },
    {
      provider: "Google LLC",
      service:
        "Firebase, Google Mobile Ads, embedded YouTube player, and Gmail",
      relationship: "Data processor and independent service provider",
      transferBasis:
        "Overseas processing and storage necessary to provide the service, consent where required, or the user's feature or inquiry request",
      data: "Content requests; app, device, operating system, language, network and IP information; usage, error, and notification records; notification tokens; advertising identifiers, consent, and interactions; YouTube playback; and email inquiries",
      purpose:
        "To synchronize content, analyze and improve the app, provide notifications, ads and rewards, play YouTube videos, and answer email inquiries",
      location:
        "The United States and other countries where Google and its processors provide services",
      timingAndMethod:
        "Transferred over an encrypted network or directly from the user's device when the relevant feature, ad, video, or email is used",
      retention:
        "According to Google's service settings and privacy policies; email inquiries are retained for one year after resolution",
      refusalAndEffect:
        "Users can change notification and advertising settings or avoid video and email features. Blocking required communications limits the relevant features.",
      policyUrl: privacyLinks.googlePrivacy,
    },
  ],
} satisfies EyeconsPrivacyPolicy;
